import pandas as pd
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows

# Datos de las pruebas
pruebas = [
    {"ID": 1, "Nombre de la prueba": "Verificar campo 'quantity' en modelo 'Order'", "Tipo": "Funcionalidad", "Resultado esperado": "Valor por defecto en 'quantity'", "Resultado obtenido": "Valor por defecto no definido", "Modulo a probar": "Modelo 'Order'", "Resultado": "Fallido", "Candidato a automatizar": "Sí", "Observación": "Añadir valor por defecto a 'quantity'", "Responsable ejecución": "Desarrollador", "Complejidad": "Media"},
    {"ID": 2, "Nombre de la prueba": "Validar manejo de cantidad en 'add_to_cart'", "Tipo": "Funcionalidad", "Resultado esperado": "Cantidad manejada correctamente", "Resultado obtenido": "Cantidad no manejada correctamente", "Modulo a probar": "Vista 'add_to_cart'", "Resultado": "Fallido", "Candidato a automatizar": "Sí", "Observación": "Corregir manejo de cantidad", "Responsable ejecución": "Desarrollador", "Complejidad": "Alta"},
    {"ID": 3, "Nombre de la prueba": "Registro correcto del filtro 'multiply'", "Tipo": "Interfaz", "Resultado esperado": "Filtro 'multiply' registrado correctamente", "Resultado obtenido": "Filtro 'multiply' no registrado", "Modulo a probar": "Filtro 'multiply'", "Resultado": "Fallido", "Candidato a automatizar": "No", "Observación": "Registrar filtro 'multiply'", "Responsable ejecución": "Desarrollador", "Complejidad": "Baja"},
    {"ID": 4, "Nombre de la prueba": "Agregar productos al carrito", "Tipo": "Funcionalidad", "Resultado esperado": "Productos añadidos correctamente", "Resultado obtenido": "Error 404", "Modulo a probar": "Vista 'add_to_cart'", "Resultado": "Fallido", "Candidato a automatizar": "Sí", "Observación": "Corregir ruta de 'add_to_cart'", "Responsable ejecución": "Desarrollador", "Complejidad": "Alta"},
    {"ID": 5, "Nombre de la prueba": "Mostrar productos en la tienda", "Tipo": "Funcionalidad", "Resultado esperado": "Productos visibles en la tienda", "Resultado obtenido": "Productos no visibles", "Modulo a probar": "Vista de tienda", "Resultado": "Fallido", "Candidato a automatizar": "No", "Observación": "Revisar lógica de visualización de productos", "Responsable ejecución": "Desarrollador", "Complejidad": "Media"},
    {"ID": 6, "Nombre de la prueba": "Verificar rutas en URLs", "Tipo": "Sintaxis", "Resultado esperado": "Rutas sin errores", "Resultado obtenido": "Errores de ruteo", "Modulo a probar": "Configuración de URLs", "Resultado": "Fallido", "Candidato a automatizar": "Sí", "Observación": "Corregir errores de ruteo", "Responsable ejecución": "Desarrollador", "Complejidad": "Baja"},
    {"ID": 7, "Nombre de la prueba": "Validar autenticación y autorización", "Tipo": "Funcionalidad", "Resultado esperado": "Autenticación y autorización correctas", "Resultado obtenido": "Problemas en autenticación", "Modulo a probar": "Sistema de autenticación", "Resultado": "Fallido", "Candidato a automatizar": "Sí", "Observación": "Revisar lógica de autenticación y autorización", "Responsable ejecución": "Desarrollador", "Complejidad": "Alta"},
    {"ID": 8, "Nombre de la prueba": "Validar integración de pagos", "Tipo": "Funcionalidad", "Resultado esperado": "Pagos procesados correctamente", "Resultado obtenido": "Pagos no procesados", "Modulo a probar": "Sistema de pagos", "Resultado": "Fallido", "Candidato a automatizar": "Sí", "Observación": "Revisar integración con sistema de pagos", "Responsable ejecución": "Desarrollador", "Complejidad": "Alta"},
    {"ID": 9, "Nombre de la prueba": "Verificar reporte de ventas", "Tipo": "Funcionalidad", "Resultado esperado": "Reporte de ventas generado correctamente", "Resultado obtenido": "Reporte de ventas no generado", "Modulo a probar": "Módulo de reportes", "Resultado": "Fallido", "Candidato a automatizar": "Sí", "Observación": "Revisar lógica de generación de reportes", "Responsable ejecución": "Desarrollador", "Complejidad": "Media"},
    {"ID": 10, "Nombre de la prueba": "Verificar sistema de notificaciones", "Tipo": "Funcionalidad", "Resultado esperado": "Notificaciones enviadas correctamente", "Resultado obtenido": "Notificaciones no enviadas", "Modulo a probar": "Sistema de notificaciones", "Resultado": "Fallido", "Candidato a automatizar": "No", "Observación": "Revisar integración con sistema de notificaciones", "Responsable ejecución": "Desarrollador", "Complejidad": "Media"},
    {"ID": 11, "Nombre de la prueba": "Validar actualización de stock", "Tipo": "Funcionalidad", "Resultado esperado": "Stock actualizado correctamente", "Resultado obtenido": "Stock no actualizado", "Modulo a probar": "Sistema de inventario", "Resultado": "Fallido", "Candidato a automatizar": "Sí", "Observación": "Revisar lógica de actualización de stock", "Responsable ejecución": "Desarrollador", "Complejidad": "Alta"},
    {"ID": 12, "Nombre de la prueba": "Verificar envío de correos", "Tipo": "Funcionalidad", "Resultado esperado": "Correos enviados correctamente", "Resultado obtenido": "Correos no enviados", "Modulo a probar": "Sistema de correos", "Resultado": "Fallido", "Candidato a automatizar": "Sí", "Observación": "Revisar integración con sistema de correos", "Responsable ejecución": "Desarrollador", "Complejidad": "Media"},
    {"ID": 13, "Nombre de la prueba": "Validar registro de usuarios", "Tipo": "Funcionalidad", "Resultado esperado": "Usuarios registrados correctamente", "Resultado obtenido": "Usuarios no registrados", "Modulo a probar": "Sistema de registro", "Resultado": "Fallido", "Candidato a automatizar": "Sí", "Observación": "Revisar lógica de registro de usuarios", "Responsable ejecución": "Desarrollador", "Complejidad": "Alta"},
    {"ID": 14, "Nombre de la prueba": "Verificar lógica de descuentos", "Tipo": "Funcionalidad", "Resultado esperado": "Descuentos aplicados correctamente", "Resultado obtenido": "Descuentos no aplicados", "Modulo a probar": "Sistema de descuentos", "Resultado": "Fallido", "Candidato a automatizar": "No", "Observación": "Revisar lógica de aplicación de descuentos", "Responsable ejecución": "Desarrollador", "Complejidad": "Media"},
    {"ID": 15, "Nombre de la prueba": "Validar generación de facturas", "Tipo": "Funcionalidad", "Resultado esperado": "Facturas generadas correctamente", "Resultado obtenido": "Facturas no generadas", "Modulo a probar": "Sistema de facturación", "Resultado": "Fallido", "Candidato a automatizar": "Sí", "Observación": "Revisar lógica de generación de facturas", "Responsable ejecución": "Desarrollador", "Complejidad": "Alta"},
    {"ID": 16, "Nombre de la prueba": "Verificar lógica de búsqueda", "Tipo": "Funcionalidad", "Resultado esperado": "Búsqueda funcionando correctamente", "Resultado obtenido": "Búsqueda no funciona", "Modulo a probar": "Sistema de búsqueda", "Resultado": "Fallido", "Candidato a automatizar": "No", "Observación": "Revisar lógica de búsqueda", "Responsable ejecución": "Desarrollador", "Complejidad": "Media"},
    {"ID": 17, "Nombre de la prueba": "Validar exportación de datos", "Tipo": "Funcionalidad", "Resultado esperado": "Datos exportados correctamente", "Resultado obtenido": "Datos no exportados", "Modulo a probar": "Sistema de exportación", "Resultado": "Fallido", "Candidato a automatizar": "Sí", "Observación": "Revisar integración con sistema de exportación", "Responsable ejecución": "Desarrollador", "Complejidad": "Alta"},
    {"ID": 18, "Nombre de la prueba": "Verificar lógica de filtros", "Tipo": "Funcionalidad", "Resultado esperado": "Filtros funcionando correctamente", "Resultado obtenido": "Filtros no funcionan", "Modulo a probar": "Sistema de filtros", "Resultado": "Fallido", "Candidato a automatizar": "No", "Observación": "Revisar lógica de filtros", "Responsable ejecución": "Desarrollador", "Complejidad": "Media"}
]

# Crear DataFrame para las pruebas
df_pruebas = pd.DataFrame(pruebas)

# Crear un nuevo libro de trabajo y hoja
wb = Workbook()
ws_pruebas = wb.active
ws_pruebas.title = "Pruebas"

# Añadir el resumen de pruebas a la hoja de pruebas
for r in dataframe_to_rows(df_pruebas, index=False, header=True):
    ws_pruebas.append(r)

# Guardar el archivo Excel
wb.save("Pruebas_de_Integracion.xlsx")

print("Archivo Excel creado exitosamente.")