# Generated by Django 5.0.6 on 2024-07-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_order_product_customuser_rut_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Desconocida', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='0', max_length=20, unique=True),
        ),
    ]
