# Generated by Django 5.0.6 on 2024-07-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_product_brand_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
    ]
