# Generated by Django 5.0.6 on 2024-07-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_product_brand_remove_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('performance', models.TextField()),
                ('report_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('store_performance', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Desconocida', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Categoría desconocida', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='404', max_length=20, unique=True),
        ),
    ]
