# Generated by Django 5.0.6 on 2024-07-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_performancereport_salesreport_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
