# Generated by Django 5.0.6 on 2024-07-05 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_product_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='code',
            new_name='product_id',
        ),
    ]
