# Generated by Django 5.0.6 on 2024-07-05 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_product_name_alter_product_product_id'),
    ]

    operations = [
    ]
