# Generated by Django 5.0.6 on 2024-07-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_alter_order_status_alter_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Categoría desconocida', max_length=50),
        ),
    ]
