# Generated by Django 5.0.6 on 2024-07-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='code',
            new_name='product_id',
        ),
    ]
